# Interactive component

<script src="https://unpkg.com/d3-regression@1.3.9/dist/d3-regression.min.js"></script>
<script src="https://d3js.org/d3.v7.js"></script>

<div id="plot"></div>

<script>
		var w = 600;
		var h = 300;
		var padding = 40;

		//Create scale functions
		var xScale = d3.scaleLinear()
		.domain([0, 1])
		.range([padding, w - padding / 2]);

		var yScale = d3.scaleLinear()
		.domain([0, 1])
		.range([h - padding, padding / 2]);

		// define X axis
		var xAxis = d3.axisBottom()
		.scale(xScale)
		.ticks(5);

		//Define Y axis
		var yAxis = d3.axisLeft()
		.scale(yScale)
		.ticks(5);

		var svg = d3.select("#plot")
		  .append("svg")
		  .attr("width", w)
		  .attr("height", h);

		var linearRegression = d3.regressionLinear()
       .x(d => d.attend)
       .y(d => d.grad)

		//Create X axis
		svg.append("g")
		.attr("id", "xaxis")
		.attr("transform", "translate(0," + (h - padding) + ")")
		.call(xAxis);

		//Create Y axis
		svg.append("g")
		.attr("id", "yaxis")
		.attr("transform", "translate(" + padding + ",0)")
		.call(yAxis);

		svg.append("text")
		  .attr("x", w/2)
		  .attr("y", h/2)
		  .attr("id", "nm");
		
		svg.append("text")
    .attr("class", "x label")
    .attr("text-anchor", "end")
    .attr("x", w - 60)
    .attr("y", h -3 )
    .text("Character Owning Rate Among all Players");
    
    svg.append("text")
    .attr("class", "y label")
    .attr("text-anchor", "end")
    .attr("y", 5)
    .attr("dy", ".5em")
    .attr("transform", "rotate(-90)")
    .text("Percentage of Appearance in Abyss");

		  var rowConverter = function (d) {
		    	if (!isNaN(d.rate) && !isNaN(d.rate)) {
		    return {
					owning: +d.rate,
					appearance: +d.n,
					name: d.avatar
				}
		  }
		};

		d3.csv("https://raw.githubusercontent.com/gzmason/Genshin-Impact-Analysis/main/data/owning_and_appearance_rate.csv", rowConverter)
		  .then(function(data) {
      console.log(data);
      
		  xScale
		    .domain([d3.min(data.map(d => d.owning)
		               .filter(d => d > 0)),
					       d3.max(data.map(d => d.owning))]);

		  yScale
			  .domain([d3.min(data.map(d => d.appearance)),
			           d3.max(data.map(d => d.appearance))]);

				d3.select("#yaxis").call(yAxis);

				d3.select("#xaxis").call(xAxis);

		  var allCircles = svg.selectAll("circle")
					.data(data)
					.enter()
					.append("circle")
					.attr("cx", d => xScale(d.owning))
					.attr("cy", d => yScale(d.appearance))
					.attr("r", 5)
					.attr("fill", "black")
					.attr("fill-opacity", ".5")
					.on("mouseover", function () {
					  var school = d3.select(this);
					  school
					    .attr("r", "5");
					  svg.append("g")
					    .attr("id", "temp")
					    .append("text")
					    .attr("fill", "purple")
					    .text(school.datum().name)
					    .attr("x", school.attr("cx"))
					    .attr("y", school.attr("cy"))
					    .style("text-anchor", function () {
							  if (+school.attr("cx") > d3.mean(xScale.range())) {
								  return "end";
							  } else {
								  return "start";
							  }
						});
					})
					.on("mouseout", function () {
					  d3.select(this).attr("r", "3");
					  d3.select("g#temp").remove();
					});

		})
		.catch(function(error) {
					svg.select("text#nm").text("Error loading data.")
					});
		</script>

This is an interactive scatter plot on Percentage of Appearance in the Abyss versus Character Owning Rate. The definition of Percentage of Appearance is the same as in previous plots -- number of Abyss challenges that players choose to use this character divided by total number of challenges players make. The definition of Character Owning Rate is how much percent of players own this character.

Each point is one character. Points closer to the top are characters who appear more frequently in Abyss, and points closer to the right are characters who are owned by many players. By moving the mouse onto a point, the name of that character is shown.