# Conclusion

The project serves as a great opportunity for us to apply what we learned in data analysis and visualization to a topic of our interests, Genshin Impact. We mainly want to derive insights on how to evaluate a character strength based on battle data against hardest end-game content, the Abyss. There are few key takeaways:
- 4-star characters generally perform quite poor in terms of usage rate, which indicates that players owning these characters would probably not use them in clearing the Abyss. Nonetheless, there are a few exceptions that have extraordinarily high usage rate even than other 5-star characters, namely Bennett, Xingqiu, Xiangling, and Diona. It is recommended that players should try to acquire these characters.

- A few 5-star characters lie in the high usage rate region > 75%. These characters should also be considered worth drawing. 

- In terms of resource worthiness, Venti, Zhongli, Kamisato Ayaka, and Kaedehara Kazuha are among the characters list that does not require enriching, or additional constellation level to work. 

- Hydro, anemo, and cyro overall have best usage rate performances. Electro and geo generally perform worst with few exceptions.

Of course there are several limitations that worth mentioning. The data we collected span only 4 sessions of Abyss, which is quite few considering there are 2 sessions every month and Genshin Impact started last October. We cannot observe a good overall trend for character strength given so little data we use. Also, we focus a lot on appearance rate and usage rate to analyze our data, yet there should be other evaluation metrics that we can establish, and comparison between these metrics would be even more meaningful.


future improvements 